
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class VentanaModificar extends javax.swing.JDialog {

    /**
     * Creates new form VentanaModificar
     */
    private VentanaFormulario ventana;
    public VentanaModificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ventana = (VentanaFormulario)parent;
        this.getContentPane().setBackground(new Color (235, 184, 255));
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesTexto = new javax.swing.JComboBox<>();
        respuestaTexto = new javax.swing.JTextField();
        botonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        opcionesTexto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Año Estreno", "País Origen", "Director", "Edad Director", "Género1", "Género2", "Actor1", "Actor2", "Compositor" }));

        botonModificar.setBackground(new java.awt.Color(204, 110, 253));
        botonModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respuestaTexto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 112, Short.MAX_VALUE)
                        .addComponent(botonModificar)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuestaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonModificar)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        //Botón usado para remplazar el texto del elemento que quiera el usuario
        //No se permite añadir texto vacio
        String elemento = opcionesTexto.getSelectedItem().toString();
        String respuesta = respuestaTexto.getText();
        //Validación
        if(elemento.equals("Año Estreno") && !comprobarTexto(respuesta) && respuesta.length()<5|| elemento.equals("Edad Director") && !comprobarTexto(respuesta) && respuesta.length()<4 
           || !elemento.equals("Título") && comprobarTexto(respuesta) && respuesta.length()>2|| elemento.equals("Título") && respuesta.length()>2)
        {
            ventana.jaxb.modificarJAXB(elemento, respuesta);
            ventana.asignaTexto();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
        } 
    }//GEN-LAST:event_botonModificarActionPerformed

    public boolean comprobarTexto(String texto)//Método usado para impedir u obligar a que escriban números en el nombre
    {
        for(int i = 0; i<10; i++)
        {
            if(texto.contains(""+i))
            {
                return false;
            }
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaModificar dialog = new VentanaModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificar;
    private javax.swing.JComboBox<String> opcionesTexto;
    private javax.swing.JTextField respuestaTexto;
    // End of variables declaration//GEN-END:variables
}
